'''
Created on Feb 25, 2013

@author: cmcculloch
'''
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Feb 26 09:46:02 2013

import wx

# begin wxGlade: extracode
# end wxGlade



class SuiteFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SuiteFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizerSuites_staticbox = wx.StaticBox(self, -1, "Test Suites")
        self.treeCode = wx.TreeCtrl(self, -1, style=wx.TR_HAS_BUTTONS|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.textInfo = wx.TextCtrl(self, -1, "Script Information", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.textCode = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        
        # Menu Bar
        self.mainFrameMenu = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "&Reload", "Reload the tree of code", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Re&vert", "Discard changes and revert to last known state", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "E&xit", "", wx.ITEM_NORMAL)
        self.mainFrameMenu.Append(wxglade_tmp_menu, "&File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "&Connect", "", wx.ITEM_NORMAL)
        self.mainFrameMenu.Append(wxglade_tmp_menu, "&Database")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu_sub = wx.Menu()
        wxglade_tmp_menu_sub.Append(wx.NewId(), "Scrip&t", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu_sub.Append(wx.NewId(), "&Module", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu_sub.Append(wx.NewId(), "&Block", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu_sub.Append(wx.NewId(), "&Suite", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendMenu(wx.NewId(), "&Increment version", wxglade_tmp_menu_sub, "")
        wxglade_tmp_menu_sub = wx.Menu()
        wxglade_tmp_menu_sub.Append(wx.NewId(), "Scrip&t", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu_sub.Append(wx.NewId(), "&Module", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu_sub.Append(wx.NewId(), "&Block", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu_sub.Append(wx.NewId(), "&Suite", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendMenu(wx.NewId(), "&Branch version", wxglade_tmp_menu_sub, "")
        self.mainFrameMenu.Append(wxglade_tmp_menu, "&Commit")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "&Help", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "&About", "", wx.ITEM_NORMAL)
        self.mainFrameMenu.Append(wxglade_tmp_menu, "&Help")
        self.SetMenuBar(self.mainFrameMenu)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.onFileReload, id=-1)
        self.Bind(wx.EVT_MENU, self.onFileRevert, id=-1)
        self.Bind(wx.EVT_MENU, self.onFileExit, id=-1)
        self.Bind(wx.EVT_MENU, self.onDatabaseConnect, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitIncrementScript, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitIncrementModule, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitIncrementBlock, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitIncrementSuite, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitBranchScript, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitBranchModule, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitBranchBlock, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuCommitBranchSuite, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuHelpHelp, id=-1)
        self.Bind(wx.EVT_MENU, self.onMenuHelpAbout, id=-1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SuiteFrame.__set_properties
        self.SetTitle("Cthulu Database Interface")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SuiteFrame.__do_layout
        sizerMain = wx.BoxSizer(wx.VERTICAL)
        sizerMainVertical = wx.BoxSizer(wx.VERTICAL)
        sizerMainCode = wx.BoxSizer(wx.HORIZONTAL)
        sizerSelector = wx.BoxSizer(wx.HORIZONTAL)
        sizerSuites = wx.StaticBoxSizer(self.sizerSuites_staticbox, wx.VERTICAL)
        sizerSuites.Add(self.treeCode, 1, wx.EXPAND, 0)
        sizerSelector.Add(sizerSuites, 1, wx.EXPAND, 0)
        sizerMainVertical.Add(sizerSelector, 1, wx.EXPAND, 0)
        sizerMainCode.Add(self.textInfo, 1, wx.EXPAND, 0)
        sizerMainCode.Add(self.textCode, 4, wx.EXPAND, 0)
        sizerMainVertical.Add(sizerMainCode, 3, wx.EXPAND, 0)
        sizerMain.Add(sizerMainVertical, 1, wx.EXPAND, 0)
        self.SetSizer(sizerMain)
        sizerMain.Fit(self)
        self.Layout()
        # end wxGlade

    def onFileReload(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onFileReload' not implemented!"
        event.Skip()

    def onFileRevert(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onFileRevert' not implemented!"
        event.Skip()

    def onFileExit(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onFileExit' not implemented!"
        event.Skip()

    def onDatabaseConnect(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onDatabaseConnect' not implemented!"
        event.Skip()

    def onMenuCommitIncrementScript(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitIncrementScript' not implemented!"
        event.Skip()

    def onMenuCommitIncrementModule(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitIncrementModule' not implemented!"
        event.Skip()

    def onMenuCommitIncrementBlock(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitIncrementBlock' not implemented!"
        event.Skip()

    def onMenuCommitIncrementSuite(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitIncrementSuite' not implemented!"
        event.Skip()

    def onMenuCommitBranchScript(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitBranchScript' not implemented!"
        event.Skip()

    def onMenuCommitBranchModule(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitBranchModule' not implemented!"
        event.Skip()

    def onMenuCommitBranchBlock(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitBranchBlock' not implemented!"
        event.Skip()

    def onMenuCommitBranchSuite(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuCommitBranchSuite' not implemented!"
        event.Skip()

    def onMenuHelpHelp(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuHelpHelp' not implemented!"
        event.Skip()

    def onMenuHelpAbout(self, event): # wxGlade: SuiteFrame.<event_handler>
        print "Event handler `onMenuHelpAbout' not implemented!"
        event.Skip()

# end of class SuiteFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainFrame = SuiteFrame(None, -1, "")
    app.SetTopWindow(mainFrame)
    mainFrame.Show()
    app.MainLoop()
